services:
  mongo:
    image: mongo:7
    container_name: mongodb
    hostname: mongodb
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=faceit
    volumes:
      - mongo:/data/db
    networks:
      - default
    ports:
      - "27017:27017"
    healthcheck:
      test: [
        "CMD",
        "mongosh",
        "--quiet",
        "localhost:27017/faceit",
        "--eval",
        "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
      ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  user-service:
    hostname: user-service
    image: user-service
    build:
      context: .
      dockerfile: ./Dockerfile
      target: app
    restart: on-failure
    environment:
      - MONGODB_URI=mongodb://mongo:mongo@mongodb:27017/faceit?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - default
    ports:
      - "80:80"

networks:
  default:
    driver: bridge

volumes:
  mongo:
    driver: local